name: Docker build
on:
    push:
        branches:
        - main
        - dev
jobs:
    builddocker:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            
            - name: Install docker
              run: |
                sudo apt-get update
                sudo apt-get install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
            
            - name: Build Docker image
              run: |
                  docker build -t fastapi-welcome:latest ./src
            
            - name: List Docker images
              run: |
                    docker images

  
