name: Multi events
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
env:
  api_username: ${{ secrets.AWS_KEY }}

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Basic Information"
        run: |
          echo "alldata ${{ env.api_username }}"
          echo "REF: $GITHUB_REF"
          echo "Job ID: $GITHUB_JOB"
          echo "Action: $GITHUB_ACTION"
          echo "Actor: $GITHUB_ACTOR"