name: Repository Trigger

on:
  repository_dispatch:
    types: [test_result]

jobs:
  run_if_success:
    if: ${{ github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.upgrade_status.outputs.ENVIRONMENT }}

    steps:
      - name: Check Upgrade Status
        id: upgrade_status
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
          ENVIRONMENT: ${{ github.event.client_payload.env }}
        run: |
          echo $MESSAGE
          echo "Server to run is: $ENVIRONMENT"
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_OUTPUT  # Set output

  test_run:
    needs: run_if_success
    runs-on: ubuntu-latest
    steps:
      - name: Test Runs
        run: |
          echo "The shared variable is: ${{ needs.run_if_success.outputs.ENVIRONMENT }}"
