name: Run Test suite

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose SUT environment'
        required: true
        type: choice
        options:
          - cn1000
          - cn8000
          - cn8001
          - cn8006
          - cn8007
          - cn8008
          - cn8009
          - cnboeing
          - cnverizon
          - cn8012
        default: cn8006
      suite_name:
        description: 'Choose SUITE'
        required: true
        type: choice
        options:
          - API
          - E2E
          - Windows_E2E
          - Android_E2E
          - IOS_E2E
          - MACOS_E2E
          - Custom_suite
        default: API
      custom_run:
        description: 'Custom pytest command (used only with Custom_suite)'
        required: false
        default: ''

env:
  DOCKER_IMAGE: uem-automation
  SLACK: false
  TAG: main

jobs:
  test-run:
    name: Run Test Suite
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set variables for branch name and image tag
        id: set-output
        run: |
          if [ -n "${GITHUB_HEAD_REF}" ]; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          else
            BRANCH_NAME="${GITHUB_REF_NAME}"
          fi
          TAG=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9]/-/g')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Set test suite variables
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          
          SUITE="${{ github.event.inputs.suite_name }}"
          CUSTOM_RUN="${{ github.event.inputs.custom_run }}"

          case "$SUITE" in
            "API")
              TEST_COMMAND="pytest -m api -n auto"
              ;;
            "Windows_E2E")
              TEST_COMMAND="pytest -m 'windows and e2e' -n8 --reruns 1"
              ;;
            "Android_E2E")
              TEST_COMMAND="pytest -m 'android and e2e' -n4 --reruns 1"
              ;;
            "IOS_E2E")
              TEST_COMMAND="pytest -m 'ios and e2e' -n4 --reruns 1"
              ;;
            "MACOS_E2E")
              TEST_COMMAND="pytest -m 'macos and e2e' -n3 --reruns 1"
              ;;
            "Custom_suite")
              if [ -z "$CUSTOM_RUN" ] || [ "$CUSTOM_RUN" = "null" ]; then
                echo "Error: 'Custom_suite' selected but 'custom_run' input is empty."
                exit 1
              fi
              echo "Using custom run command: $CUSTOM_RUN"
              echo "TEST_COMMAND=$CUSTOM_RUN" >> $GITHUB_ENV
              ;;
            *)
              echo "Error: Unknown suite selected."
              exit 1
              ;;
          esac

          echo "TEST_COMMAND=$TEST_COMMAND" >> $GITHUB_ENV
          echo "SUITE_NAME=UEM $SUITE tests | ${{ github.event.inputs.environment }} | TEST_COMMAND=$TEST_COMMAND | BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
