name: Run Test suite

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose SUT environment'
        required: true
        type: choice
        options:
          - cn1000
          - cn8000
          - cn8001
          - cn8006
          - cn8007
          - cn8008
          - cn8009
          - cnboeing
          - cnverizon
          - cn8012
        default: cn8006
      suite_name:
        description: 'Choose SUITE'
        required: true
        type: choice
        options:
          - API
          - E2E
          - Windows_E2E
          - Android_E2E
          - IOS_E2E
          - MACOS_E2E
        default: API

env:
  DOCKER_IMAGE: uem-automation
  SLACK: false
  TAG: main

jobs:
  test-run:
    name: Run Test Suite
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu_latest
    steps:
      - name: Set variables for branch name and image tag
        id: set-output
        run: |
          if [ -n "${GITHUB_HEAD_REF}" ]; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          else
            BRANCH_NAME="${GITHUB_REF_NAME}"
          fi
          TAG=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9]/-/g')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Set test suite variables
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          case "${{ github.event.inputs.suite_name }}" in
            "API")
              echo "TEST_COMMAND=pytest -m api -n auto" >> $GITHUB_ENV
              ;;
            "Windows_E2E")
              echo "TEST_COMMAND=pytest -m 'windows and e2e' -n8 --reruns 1" >> $GITHUB_ENV
              ;;
            "Android_E2E")
              echo "TEST_COMMAND=pytest -m 'android and e2e' -n4 --reruns 1" >> $GITHUB_ENV
              ;;\
            "IOS_E2E")
              echo "TEST_COMMAND=pytest -m 'ios and e2e' -n4 --reruns 1" >> $GITHUB_ENV
              ;;
            "MACOS_E2E")
              echo "TEST_COMMAND=pytest -m 'macos and e2e' -n3 --reruns 1" >> $GITHUB_ENV
              ;;
          esac
      
          echo "SUITE_NAME=UEM ${{ github.event.inputs.suite_name }} tests | ${{ github.event.inputs.environment }} | $BRANCH_NAME" >> $GITHUB_ENV

      