name: Cron Job

on:
  schedule:
    # Schedule for Environment 1 (e.g., every 5 minutes)
    - cron: "*/5 * * * *"
    # Schedule for Environment 2 (e.g., daily at 2:00 AM)
    - cron: "0 2 * * *"
    # Schedule for Environment 3 (e.g., daily at 3:00 AM)
    - cron: "0 3 * * *"

jobs:
  set-variables:
    name: Set Variables
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-output.outputs.environment }}
    steps:
      - name: Determine Triggered Environment
        id: set-output
        run: |
          CURRENT_TIME=$(date +"%H:%M")
          case "$CURRENT_TIME" in
            "*/5") echo "environment=CNVERIZON" >> $GITHUB_OUTPUT ;;
            "02:00") echo "environment=CNPWC" >> $GITHUB_OUTPUT ;;
            "03:00") echo "environment=CNBOIENG" >> $GITHUB_OUTPUT ;;
            *) echo "Unknown schedule triggered"; exit 1 ;;
          esac

  run_test:
    name: Run CFLOW Suite
    runs-on: lnxbuild-gh
    needs: set-variables
    env:
      ENVIRONMENT: ${{ needs.set-variables.outputs.environment }}
    steps:
      - name: Check Environment
        run: |
          echo "Running for environment: ${{ env.ENVIRONMENT }}"

      - name: Run Script for CNVERIZON
        if: env.ENVIRONMENT == 'CNVERIZON'
        run: |
          echo "Execute tasks for CNVERIZON"

      - name: Run Script for CNPWC
        if: env.ENVIRONMENT == 'CNPWC'
        run: |
          echo "Execute tasks for CNPWC"

      - name: Run Script for CNBOIENG
        if: env.ENVIRONMENT == 'CNBOIENG'
        run: |
          echo "Execute tasks for CNBOIENG"
