name: Cron Job

on:
  schedule:
    # Schedule for Environment 1 (e.g., every 5 minutes)
    - cron: "*/5 * * * *"
    # Schedule for Environment 2 (e.g., daily at 2:00 AM)
    - cron: "0 2 * * *"
    # Schedule for Environment 3 (e.g., daily at 3:00 AM)
    - cron: "0 3 * * *"

jobs:
  set-variables:
    name: hello_world
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-output.outputs.environment }}
    steps:
      - name: Determine Triggered Environment
        id: set-output
        run: |
          case "${{ github.event.schedule }}" in
            "*/5 * * * *") echo "environment=CNVERIZON" >> $GITHUB_OUTPUT ;;
            *) echo "Unknown schedule triggered"; exit 1 ;;
          esac
  run_test:
    name: Run CFLOW suite
    runs-on: lnxbuild-gh
    needs: set-variables
    env:
      ENVIRONMENT: ${{ needs.set-variables.outputs.environment }}
      steps:
        - name: Check Environment
          run: |
            echo "Running for environment: ${{ env.ENVIRONMENT }}"

        - name: Run Script
          if: env.ENVIRONMENT == 'CNVERIZON'
          run: |
            echo "Execute tasks for cnverizon"

        - name: Run Script
          if: env.ENVIRONMENT == 'cnpwc'
          run: |
            echo "Execute tasks for cnpwc"

        - name: Run Script
          if: env.ENVIRONMENT == 'cnboieng'
          run: |
            echo "Execute tasks for cnboieng"
