name: Cron Job

on:
  schedule:
    # Schedule for Environment 1 (e.g., every 5 minutes)
    - cron: "*/5 * * * *"
    # Schedule for Environment 2 (e.g., daily at 2:00 AM)
    - cron: "0 2 * * *"
    # Schedule for Environment 3 (e.g., daily at 3:00 AM)
    - cron: "0 3 * * *"

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Triggered Environment
        id: determine_env
        run: |
          case "${{ github.event.schedule }}" in
            "*/5 * * * *") echo "env=cnverizon" >> $GITHUB_ENV ;;
            "0 2 * * *") echo "env=cnpwc" >> $GITHUB_ENV ;;
            "0 3 * * *") echo "env=cnboieng" >> $GITHUB_ENV ;;
            *) echo "Unknown schedule triggered"; exit 1 ;;
          esac

      - name: Check Environment
        run: |
          echo "Running for environment: ${{ env.env }}"

      - name: Run Script
        if: env.env == 'cnverizon'
        run: |
          echo "Execute tasks for cnverizon"

      - name: Run Script
        if: env.env == 'cnpwc'
        run: |
          echo "Execute tasks for cnpwc"

      - name: Run Script
        if: env.env == 'cnboieng'
        run: |
          echo "Execute tasks for cnboieng"
