name: Cron Job
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - cn1000
          - cn8000
          - cn8006
          - cn8008
          - cnverizon
        default: cn8000

jobs:
  set-variables:
    name: Set variables
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-output.outputs.environment }}
    steps:
      - name: Set default environment for scheduled workflow
        id: set-output
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            if [ "${{ github.event.schedule }}" == "*/5 * * * *"" ]; then
              echo "Scheduled run detected. Setting environment: cnverizon"
              echo "environment=cnverizon" >> $GITHUB_OUTPUT
            fi
          else
            echo "Manual run detected. Setting environment to: ${{ github.event.inputs.environment }}"
            echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          fi


  hello_world:
    runs-on: ubuntu-latest
    needs: set-variables
    env:
      ENVIRONMENT: ${{ needs.set-variables.outputs.environment }}
    steps:
      - name: Echo current time
        run: |
          echo "Starting the line"
          echo $ENVIRONMENT

