name: Cron Job
on:
  schedule:
    # Schedule for Environment 1 (e.g., daily at 1:00 AM)
    - cron: "*/5 * * * *"
    # Schedule for Environment 2 (e.g., daily at 2:00 AM)
    - cron: "0 2 * * *"
    # Schedule for Environment 3 (e.g., daily at 3:00 AM)
    - cron: "0 3 * * *"

jobs:
  hello_world:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          # Map cron times to environments
          - { name: "cnverizon", schedule: "*/5 * * * *" }
          - { name: "cnpwc", schedule: "0 2 * * *" }
          - { name: "cnboieng", schedule: "0 3 * * *" }
    steps:
      - name: Check Environment
        run: |
          echo "Running for environment: ${{ matrix.env.name }} on schedule: ${{ matrix.env.schedule }}"

      - name: Run Script
        run: |
          if [ "${{ matrix.env.name }}" == "cnverizon" ]; then
            echo "Execute tasks for cnverizon";
          elif [ "${{ matrix.env.name }}" == "cnpwc" ]; then
            echo "Execute tasks for cnpwc";
          elif [ "${{ matrix.env.name }}" == "cnboieng" ]; then
            echo "Execute tasks for cnboieng";
          fi

