name: Customer Flow Regressions

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every Monday at 5 AM
  workflow_dispatch:
    inputs:
      server:
        description: "Server name for the tests"
        required: true
        default: "cnverizon"
      test_query:
        description: "Test query to filter tests"
        required: true
        default: "verizon"

jobs:
  trigger_dispatch:
    if: github.event_name == 'schedule'
    name: Trigger Workflow Dispatch
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow_dispatch
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
                  "ref": "main",
                  "inputs": {
                    "server": "cnverizon",
                    "test_query": "verizon"
                  }
                }' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow_id }}/dispatches

  test_cflow:
    if: github.event_name == 'workflow_dispatch'
    name: Run CFLOW Suite
    runs-on: ubuntu-latest
    steps:
      - name: Display Inputs
        run: |
          echo "Server: ${{ github.event.inputs.server }}"
          echo "Test Query: ${{ github.event.inputs.test_query }}"

      - name: Run Tests
        run: |
          echo "pytest -k '${{ github.event.inputs.test_query }}' --server '${{ github.event.inputs.server }}'"
