name: Customer Flow Regressions

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes (adjust as needed)
  repository_dispatch:
    types: [trigger-regression-tests]

jobs:
  trigger_test_run:
    name: Trigger Repository Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch with server details
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type": "trigger-regression-tests", "client_payload": {"server": "cnverizon", "test_query": "verizon", "tg_token": "asd"}}' \
            https://api.github.com/repos/${{ github.repository }}/dispatches

  test_cflow:
    name: Run CFLOW Suite
    runs-on: ubuntu-latest
    needs: trigger_test_run
    if: ${{ github.event_name == 'repository_dispatch' && github.event.action == 'trigger-regression-tests' }}
    steps:
      - name: Print Test Query
        run: |
          echo "Query is '${{ github.event.client_payload.test_query }}'"
          echo "Running on server '${{ github.event.client_payload.server }}'"
